services:
  app:
    build: .
    ports:
      - "8080:8080"
    #depends_on:
      #- db
    #environment:
      #SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/animals
      #SPRING_DATASOURCE_USERNAME: animal_user
      #SPRING_DATASOURCE_PASSWORD: animal_pass
      #SPRING_DATASOURCE_DRIVER: org.postgresql.Driver
      #SPRING_JPA_HIBERNATE_DDL_AUTO: update
      #SPRING_JPA_DATABASE_PLATFORM: org.hibernate.dialect.PostgreSQLDialect	
  #db:
    #image: postgres:15
    #environment:
      #POSTGRES_DB: animals
      #POSTGRES_USER: animal_user
      #POSTGRES_PASSWORD: animal_pass
    #ports:
      #- "5432:5432"